### PR TITLE
Setup correct `target`/`module`/`moduleResolution` settings for TSConfig

### PR DESCRIPTION
**Pull request by rwjblue**
This reverts some of the changes from https://github.com/data-eden/data-eden/pull/35

- Setup correct `target`/`module`/`moduleResolution` settings for TSConfig
- Had to use a deep import of `msw/lib/node/index.js` in `packages/network/__test__/fetch-test.js` in order to get TypeScript to properly typecheck the `msw`
- Adds `patch-package` infrastructure
- Add a patch for `vitest` so that we can work around issues with type resolution within `vite` (https://github.com/vitest-dev/vitest/pull/1465)

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
This change doesn't provide a usable ESM module.

**Comment by rwjblue** [comment]
> This change doesn't provide a usable ESM module.

Hmm, seems to work for me locally when linked into a consumer package... 🤔

**Comment by gabrielcsapo** [comment]
Have you tried linking this to a typescript consumer package?

**Comment by rwjblue** [comment]
> Have you tried linking this to a typescript consumer package?

Yep! The same one that you shared a screenshot from in #35.

**Review by gabrielcsapo — APPROVED** [review]
thanks for checking!

**Review by hjdivad — APPROVED** [review]
LGTM

Let's add an issue for closing the two hacks when we can, to wit:
1. remove the vitest patch
2. remove the private import from msw

**Comment by rwjblue** [comment]
Created https://github.com/data-eden/data-eden/issues/42 to track fixing those issues.

**Pull request merged**
